name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: installing package
      run: sudo apt-get install libreadline6 libreadline6-dev

    - name: building
      run: make
    - name: testings
      run: make test
